# Copyright (c) 2017 Dependable Systems Laboratory, EPFL
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This is the global configuration file for s2e-env. It describes how all
# environments are created. Normally a user would not be required to modify
# the settings in this file. Instead, a separate configuration file is
# generated for each environment. Users should modify the per-environment
# configuration file instead.

# apt-get dependencies
dependencies:
    common:
        # Build dependencies
        - build-essential
        - cmake
        - wget
        - git
        - texinfo
        - flex
        - bison
        - python3
        - python3-dev
        - python3-pip

        # Image build dependencies
        - libguestfs-tools
        - genisoimage
        - xz-utils
        - docker.io
        - p7zip-full
        - fuse
        - libhivex-bin
        - jigdo-file

        # S2E dependencies
        - libdwarf-dev
        - libelf-dev
        - libelf-dev:i386
        - libiberty-dev
        - binutils-dev
        - libreadline-dev
        - libboost-dev
        - zlib1g-dev
        - libjemalloc-dev
        - nasm
        - pkg-config
        - libmemcached-dev
        - libvdeplug-dev
        - libpq-dev
        - libc6-dev-i386
        - libboost-system-dev
        - libboost-serialization-dev
        - libboost-regex-dev
        - libprotobuf-dev
        - protobuf-compiler
        - libbsd-dev
        - libsigc++-2.0-dev
        - libsdl-dev
        - libglib2.0-dev
        - libglib2.0-dev:i386
        - libglib2.0-0:i386
        - python-docutils
        - qemu
        - mingw-w64
        - gcc-multilib
        - g++-multilib
        - libpixman-1-dev
        - libtinfo5

        # Testing dependencies
        - wine-stable

        # s2e-env dependencies
        - lcov
        - jq

    ubuntu-18:
        - lib32ncurses5
        - lib32ncurses5-dev
        - libncurses5-dev
        - libncurses5-dev:i386
        - libx32ncurses5-dev

        - python-distro

        # Image build dependencies
        - pxz

    ubuntu-20:
        - lib32ncurses-dev
        - lib32ncurses6
        - libncurses5-dev
        - libncurses5-dev:i386

        # Ubuntu 20.04 doesn't have pxz package (at least not on the release date),
        # so we install it manually
        - http://mirrors.kernel.org/ubuntu/pool/universe/p/pxz/pxz_4.999.99~beta5+gitfcfea93-2_amd64.deb


# S2E Git repos
repos:
    url: https://github.com/S2E

    # Names of git repositories
    s2e: manifest
    images:
        # Normally, guest-images and s2e-linux-kernel is handled by repo, but we
        # still need to check it out manually when using binary-only installations.
        linux: s2e-linux-kernel
        build: guest-images

required_versions:
    # Ubuntu OS major version
    ubuntu_major_ver:
        - 18
        - 20
    # images.json must have this version
    guest_images: 3

# Repo. Used for managing the S2E git repositories
repo:
    url: https://storage.googleapis.com/git-repo-downloads/repo

# Directories that will automatically be created when running ``s2e init``
dirs:
    - build
    - images
    - install
    - install/bin
    - projects
    - source

# Mapping of QEMU architecture to guest tools directory
guest_tools:
    i386: guest-tools32
    x86_64: guest-tools64

# Functions that are supported by S2E's ``FunctionModels`` plugin
function_models:
    - strcpy
    - strncpy
    - strlen
    - strcmp
    - strncmp
    - memcpy
    - memcmp
    - printf
    - fprintf
    - strcat
    - strncat
    - crc16
    - crc32

import_export:
    # Project files rewritten by the ``import_project`` and ``export_project``
    # commands
    project_files:
        - bootstrap.sh
        - launch-s2e.sh
        - library.lua
        - models.lua
        - project.json
        - s2e-config.lua
    # Files/directories that are **not** exported
    blacklist:
        - guestfs*
        - guest-tools
        - guest-tools32
        - guest-tools64
